$.fbuilder.controls['ftext'] = function() {};
$.extend(
    $.fbuilder.controls['ftext'].prototype,
    $.fbuilder.controls['ffields'].prototype, {
        title: "Untitled",
        ftype: "ftext",
        predefined: "",
        predefinedClick: false,
        required: false,
        size: "medium",
        minlength: "",
        maxlength: "",
        equalTo: "",

        show: function() {
            if (this.name == 'fieldname8_1') {
                return '<div class="fields ' + this.csslayout + '" id="field' + this.form_identifier + '-' + this.index + '"><label for="' + this.name + '">' + this.title + '' + ((this.required) ? "<span class='r'>*</span>" : "") + '</label><div class="dfield"><div class="dfieldR"><input type="radio" id="no_1" name="' + this.name + '" value="1"><label for="no_1">1</label><input type="radio" id="no_2" name="' + this.name + '" value="2"><label for="no_2">2</label><input type="radio" id="no_3" name="' + this.name + '" value="3"><label for="no_3">3</label><input type="radio" id="no_4" name="' + this.name + '" value="over 3"><label for="no_4">over 3</label></div><input id="' + this.name + '" name="' + this.name + '" minlength="' + (this.minlength) + '" maxlength="' + $.fbuilder.htmlEncode(this.maxlength) + '" ' + ((this.equalTo != "") ? "equalTo=\"#" + $.fbuilder.htmlEncode(this.equalTo + this.form_identifier) + "\"" : "") + ' class="eng field ' + this.size + ((this.required) ? " required" : "") + '" value="' + $.fbuilder.htmlEncode(this.predefined) + '" /><span class="uh">' + this.userhelp + '</span></div><div class="clearer"></div></div>';
            }
            if (this.name == 'fieldname9_1') {
                return '<div class="fields ' + this.csslayout + '" id="field' + this.form_identifier + '-' + this.index + '"><label for="' + this.name + '">' + this.title + '' + ((this.required) ? "<span class='r'>*</span>" : "") + '</label><div class="dfield"><div class="dfieldPD"><input type="radio" id="pick_up" name="' + this.name + '" value="Pick Up"><label for="pick_up">Pick Up</label><input type="radio" id="drop_off" name="' + this.name + '" value="drop_off"><label for="no_2">Drop off</label></div><input id="' + this.name + '" name="' + this.name + '" minlength="' + (this.minlength) + '" maxlength="' + $.fbuilder.htmlEncode(this.maxlength) + '" ' + ((this.equalTo != "") ? "equalTo=\"#" + $.fbuilder.htmlEncode(this.equalTo + this.form_identifier) + "\"" : "") + ' class="eng field ' + this.size + ((this.required) ? " required" : "") + '" value="' + $.fbuilder.htmlEncode(this.predefined) + '" /><span class="uh">' + this.userhelp + '</span></div><div class="clearer"></div></div>';
            }
            if (this.name == 'fieldname3_1') {
                return '<div class="fields ' + this.csslayout + '" id="field' + this.form_identifier + '-' + this.index + '"><label for="' + this.name + '">' + this.title + '' + ((this.required) ? "<span class='r'>*</span>" : "") + '</label><div class="dfield"><div class="dfieldP"><intl-tel-input name="profile[phone_number]"> </intl-tel-input> </div><input id="' + this.name + '" name="' + this.name + '" minlength="' + (this.minlength) + '" maxlength="' + $.fbuilder.htmlEncode(this.maxlength) + '" ' + ((this.equalTo != "") ? "equalTo=\"#" + $.fbuilder.htmlEncode(this.equalTo + this.form_identifier) + "\"" : "") + ' class="eng field ' + this.size + ((this.required) ? " required" : "") + '" value="' + $.fbuilder.htmlEncode(this.predefined) + '" /><span class="uh">' + this.userhelp + '</span></div><div class="clearer"></div></div>';
            }
            if (this.name == 'fieldname12_1') {
                return '<div class="fields ' + this.csslayout + '" id="field' + this.form_identifier + '-' + this.index + '"><label for="' + this.name + '">' + this.title + '' + ((this.required) ? "<span class='r'>*</span>" : "") + '</label><div class="dfield"><div class="dfieldRec"><intl-tel-input name="profile[phone_number]"> </intl-tel-input> </div><input id="' + this.name + '" name="' + this.name + '" minlength="' + (this.minlength) + '" maxlength="' + $.fbuilder.htmlEncode(this.maxlength) + '" ' + ((this.equalTo != "") ? "equalTo=\"#" + $.fbuilder.htmlEncode(this.equalTo + this.form_identifier) + "\"" : "") + ' class="eng field ' + this.size + ((this.required) ? " required" : "") + '" value="' + $.fbuilder.htmlEncode(this.predefined) + '" /><span class="uh">' + this.userhelp + '</span></div><div class="clearer"></div></div>';
            }
            if (this.name == 'fieldname6_1') {
                return '<div class="fields ' + this.csslayout + '" id="field' + this.form_identifier + '-' + this.index + '"><label for="' + this.name + '">' + this.title + '' + ((this.required) ? "<span class='r'>*</span>" : "") + '</label><div class="dfield"><div class="dfieldS" id="dfieldS"><select name="checkCountry" id="checkCountry"><option value="uk" id="fuk">UK</option><option value="myanmar" id="fMyanmar">Myanmar</option><option value="usa">USA</option><option value="australia">Australia</option><option value="egypt">Egypt</option><option value="germany">Germany</option><option value="united arab emirates">United Arab Emirates </option><option value="turkey">Turkey</option><option value="thailand">Thailand</option><option value="malaysia">Malaysia</option><option value="singapore">Singapore</option><option value="japan">Japan</option><option value="canada">Canada</option><option value="spain">Spain</option><option value="oman">Oman</option><option value="nepal">Nepal</option><option value="belgium">Belgium</option><option value="saudi arabia">Saudi Arabia</option><option value="new zealand">New Zealand</option><option value="italy">Italy</option><option value="netherlands">Netherlands</option> </select > </div > <input id="' + this.name + '" name="' + this.name + '" minlength="' + (this.minlength) + '" maxlength="' + $.fbuilder.htmlEncode(this.maxlength) + '" ' + ((this.equalTo != "") ? "equalTo=\"#" + $.fbuilder.htmlEncode(this.equalTo + this.form_identifier) + "\"" : "") + ' class="field ' + this.size + ((this.required) ? " required" : "") + '" type="text" value="' + $.fbuilder.htmlEncode(this.predefined) + '"/><span class = "uh" > ' + this.userhelp + ' </span></div> <div class= "clearer" > </div></div > ';
            }
            if (this.name == 'fieldname5_1') {
                return '<div class="fields ' + this.csslayout + '" id="field' + this.form_identifier + '-' + this.index + '"><label for="' + this.name + '">' + this.title + '' + ((this.required) ? "<span class='r'>*</span>" : "") + '</label><div class="dfield"><select name="checkFCountry" id="checkFCountry"> <option value="myanmar">Myanmar</option><option value="uk">UK</option></select><input id="' + this.name + '" name="' + this.name + '" minlength="' + (this.minlength) + '" maxlength="' + $.fbuilder.htmlEncode(this.maxlength) + '" ' + ((this.equalTo != "") ? "equalTo=\"#" + $.fbuilder.htmlEncode(this.equalTo + this.form_identifier) + "\"" : "") + ' class="field ' + this.size + ((this.required) ? " required" : "") + '" type="text" value="' + $.fbuilder.htmlEncode(this.predefined) + '"/><span class = "uh" > ' + this.userhelp + ' </span></div> <div class= "clearer" > </div></div > ';
            } else {
                return '<div class="fields ' + this.csslayout + '" id="field' + this.form_identifier + '-' + this.index + '"><label for="' + this.name + '">' + this.title + '' + ((this.required) ? "<span class='r'>*</span>" : "") + '</label><div class="dfield"><input id="' + this.name + '" name="' + this.name + '" minlength="' + (this.minlength) + '" maxlength="' + $.fbuilder.htmlEncode(this.maxlength) + '" ' + ((this.equalTo != "") ? "equalTo=\"#" + $.fbuilder.htmlEncode(this.equalTo + this.form_identifier) + "\"" : "") + ' class="field ' + this.size + ((this.required) ? " required" : "") + '" type="text" value="' + $.fbuilder.htmlEncode(this.predefined) + '"/><span class="uh">' + this.userhelp + '</span></div><div class="clearer"></div></div>';
            }
        }
    }
);